spring.application.name=desafio-anota-ai


aws.access-key-id=${AWS_ACCESS_KEY_ID:your-access-key-id}
aws.secret-access-key=${AWS_SECRET_ACCESS_KEY:your-secret-access-key}
aws.region=${AWS_REGION:us-east-2}
aws.sns.topic-arn=${AWS_SNS_TOPIC_ARN:your-sns-topic-arn}